name: le_planning
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  email_validator: ^2.1.17

flutter:
  uses-material-design: true
  assets:
    - ressources/LePlanning.png
    - ressources/SplashScreen.png

flutter_native_splash:
  color: "#42a5f5"
  image: ressources/SplashScreen.png
  
  android_12:
    color: "#FFFFFF"
    image: ressources/SplashScreen.png
    image_dark: ressources/SplashScreen.png
    color_dark: "#FFFFFF"
